FROM includeos/includeos-common:0.10.0.1

VOLUME /service
WORKDIR /service

CMD cd build && \
  export INCLUDEOS_PREFIX=/home/ubuntu/IncludeOS_install && \
  export CC=clang-3.8 && \
  export CXX=clang++-3.8 && \
  cmake .. && \
  make
