pub static RESPONSEDATA: &str = "Hello, World!";
pub static DATABASE_TYPE: &str = "postgres";
pub static DATABASE_HOST: &str = "tfb-database";
pub static DATABASE_USER_NAME: &str = "benchmarkdbuser";
pub static DATABASE_USER_PASSWORD: &str = "benchmarkdbpass";
pub static DATABASE_PORT: usize = 5432;
pub static DATABASE_NAME: &str = "hello_world";
pub static TABLE_NAME: &str = "World";
pub static ROW_LIMIT: i32 = 500;
