source 'https://rubygems.org'

gem 'activerecord', '~> 5.0.0', :require=>'active_record'
gem 'json', '~> 2.0'
gem 'passenger', '~> 5.1', :platforms=>[:ruby, :mswin], :require=>false
gem 'puma', '~> 6.4', :require=>false
gem 'sinatra', '~> 2.0', :require=>'sinatra/base'
gem 'unicorn', '~> 5.2', :platforms=>[:ruby, :mswin], :require=>false

group :mysql do
  gem 'mysql2', '~> 0.4', :platforms=>[:ruby, :mswin]
end

group :postgresql do
  gem 'pg', '1.2.3', :platforms=>[:ruby, :mswin]
end
