source 'https://rubygems.org'

gem 'activerecord', '~> 7.2', require: 'active_record'
gem 'json', '~> 2.8'
gem 'sinatra', '~> 4.0', require: 'sinatra/base'

group :mysql, optional: true do
  gem 'mysql2', '~> 0.5', :platforms=>[:ruby, :mswin]
end

group :postgresql, optional: true do
  gem 'pg', '~> 1.5', platforms: [:ruby, :mswin]
end

group :passenger, optional: true do
  gem 'passenger', '~> 6.0', platforms: [:ruby, :mswin], require: false
end

group :puma, optional: true do
  gem 'puma', '~> 6.4', require: false
end

group :unicorn do
  gem 'unicorn', '~> 6.1', platforms: [:ruby, :mswin], require: false
end

group :agoo, optional: true do
  gem 'agoo', require: false
  gem 'rackup'
end
