source 'https://rubygems.org'

gem 'activerecord', '~> 7.0', :require=>'active_record'
gem 'json', '~> 2.0'
gem 'passenger', '~> 6.0', :platforms=>[:ruby, :mswin], :require=>false
gem 'puma', '~> 6.4', :require=>false
gem 'sinatra', '~> 3.0', :require=>'sinatra/base'
gem 'unicorn', '~> 6.1', :platforms=>[:ruby, :mswin], :require=>false

group :mysql do
  gem 'mysql2', '~> 0.5', :platforms=>[:ruby, :mswin]
end

group :postgresql do
  gem 'pg', '~> 1.5', :platforms=>[:ruby, :mswin]
end
