source 'https://rubygems.org'

gem 'erubi', '~> 1.4'
gem 'json', '~> 2.0'
gem 'passenger', '~> 5.1', :platforms=>[:ruby, :mswin], :require=>false
gem 'puma', '~> 3.9.1', :require=>false
gem 'sequel', '~> 4.44'
gem 'roda', '~> 2.24'
gem 'tilt', '~> 2.0', :require=>'tilt/erb'
gem 'torquebox-web', '>= 4.0.0.beta3', '< 5', :platforms=>:jruby, :require=>false
gem 'unicorn', '~> 5.2', :platforms=>[:ruby, :mswin], :require=>false

group :mysql do
  gem 'jdbc-mysql', '~> 5.1', :platforms=>:jruby, :require=>'jdbc/mysql'
  gem 'mysql2', '~> 0.4', :platforms=>[:ruby, :mswin]
end

group :postgresql do
  gem 'jdbc-postgres', '~> 9.4', :platforms=>:jruby, :require=>'jdbc/postgres'
  gem 'pg', '~> 0.19', :platforms=>[:ruby, :mswin]
  gem 'sequel_pg', '~> 1.6', :platforms=>:ruby, :require=>false
end
