source "https://rubygems.org"

gem "erubi", "~> 1.12"
gem "json"
gem "sequel", "~> 5.67"
gem "roda", "~> 3.66"
gem "tilt", "~> 2.1", require: "tilt/erb"
gem "cgi" # Make sure the h plugin uses the faster CGI.escape_html
gem "concurrent-ruby"

group :mysql, optional: true do
  gem "trilogy", "~> 2.10"
end

group :postgresql, optional: true do
  gem "pg", "~> 1.4"
  gem "sequel_pg", "~> 1.17", require: "sequel"
end

group :iodine, optional: true do
  gem "iodine", "~> 0.7", require: false
end
