source 'https://rubygems.org'

gem 'activerecord', '~> 8.1.0', require: 'active_record'
gem 'json'
gem 'ostruct' # required for Ruby 3.5
gem 'padrino', '~> 0.16'
gem 'pg'
gem 'rack'
gem 'slim'

group :iodine, optional: true do
  gem "iodine", "~> 0.7", require: false
end
