source 'https://rubygems.org'

gem 'mysql2', '> 0.5'
gem 'json'
gem 'activerecord', '~> 8.1.0', :require => 'active_record'

gem 'slim'
gem 'padrino', '0.16.0'
gem 'rack'

group :iodine, optional: true do
  gem "iodine", "~> 0.7", require: false
end
