source 'https://rubygems.org'

gem 'mysql2', '> 0.5'
gem 'json'
gem 'activerecord', '>= 7.1', :require => 'active_record'

gem 'slim', '2.0.3'
gem 'padrino', git: 'https://github.com/padrino/padrino-framework.git'
gem 'rack'

group :puma, optional: true do
  gem 'puma', '~> 6.4', require: false
end

group :unicorn, optional: true do
  gem 'unicorn', '~> 6.1', platforms: [:ruby, :windows], require: false
end
