.TH Banana 1 "Feb 8, 2011"
.\" Please update the above date whenever this man page is modified.
.SH NAME
banana \- Monkey HTTP Daemon control script
.SH SYNOPSIS
.B banana [options]
.SH DESCRIPTION
\fBbanana\fP helps control the Monkey Server, a very small, fast and scalable web server for Linux.
This  manual  page  only  lists  the  command  line  arguments.  For further and more detailed information regarding the program configuration see the Monkey manual, found at http://monkey-project.com/documentation . 

.SH OPTIONS
This command will launch the Monkey webserver. It accepts the following subcommands:
.TP 8
.B start
Start the server.

.TP 8
.B restart
Restart the server.

.TP 8
.B stop
Stop the server.

.TP 8
.B Help
Show help (pretty obvious).

.SH BUGS
.SS Bug reports
In general, send bug reports to the bug report mailing list at <monkey@lists.monkey-project.com>. You are requested to use a descriptive subject for your email message, perhaps parts of the error message.

.SH "SEE ALSO"
\&\fImonkey\fR\|(1).

.SH AUTHOR
Eduardo Silva <edsiper@gmail.com> and the rest of the Monkey Project team.
.PP
This manpage is maintained by the Monkey HTTP Daemon Project team.
