(lang dune 2.7)
(name webmachine-tfb)

(generate_opam_files true)

(source (github TechEmpower/FrameworkBenchmarks))
(license MIT)
(authors "Robin Björklin")

(package
 (name tiny)
 (synopsis "Rudimentary implementation of the Tech Empower Benchmark suite")
 (depends
  (dune (>= 2.7.1))
  (tiny_httpd (>= 0.6))))

(package
 (name lib)
 (synopsis "WIP library")
 (depends
  (dune (>= 2.7.1))
  (biniou (>= 1.2.1))
  (yojson (>= 1.7.0))
  (atd (>= 2.2.1))
  (atdgen (>= 2.2.1))
  (atdgen-runtime (>= 2.2.1))))
