#!/bin/bash

start() {
  /opt/elasticsearch/bin/elasticsearch -d -p /ssd/elasticsearch/es.pid
}

stop() {
  kill -HUP `cat /ssd/elasticsearch/es.pid`
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 10
    start
    ;;
esac

