# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rack', '~> 3.0'
gem 'connection_pool', '~> 2.4'
gem 'jdbc-postgres', '~> 42.2', platforms: :jruby, require: 'jdbc/postgres'
gem 'json', '~> 2.8'
gem 'pg', '~> 1.5', platforms: %i[ruby mswin]
gem 'sequel'
gem 'sequel_pg', platforms: %i[ruby mswin]
gem 'tzinfo-data', '1.2023.3'

group :falcon, optional: true do
  gem 'falcon', '~> 0.47', platforms: %i[ruby mswin]
end

group :iodine, optional: true do
  gem 'iodine', '~> 0.7', platforms: %i[ruby mswin]
end

group :puma, optional: true do
  gem 'puma', '~> 6.4'
end

group :unicorn, optional: true do
  gem 'unicorn', '~> 6.1', platforms: %i[ruby mswin]
end

group :development, optional: true do
  gem 'rack-test'
  gem 'rubocop', platforms: %i[ruby mswin]
end
