# frozen_string_literal: true

source 'https://rubygems.org'

gem 'connection_pool', '~>2.4'
gem 'falcon', '~>0.42'
gem 'jdbc-postgres', '~> 42.2', platforms: :jruby, require: 'jdbc/postgres'
gem 'oj', '~> 3.14'
gem 'pg', '~>1.5' # , group: :postgresql
gem 'puma', '~> 6.2'
gem 'sequel'
gem 'sequel_pg'
gem 'tzinfo-data', '1.2023.3'
gem 'unicorn', '~> 6.1', platforms: %i[ruby mswin], require: false

group :development do
  gem 'rack-test'
  gem 'rubocop', platforms: %i[ruby mswin]
end
