# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.hostname = "FrameworkBenchmarks"
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :forwarded_port, guest: 8080, host: 28080
  config.vm.provider :virtualbox do |vb|
    vb.gui = true  
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  config.vm.synced_folder "../../..", "/FrameworkBenchmarks"
  config.vm.network "private_network", ip: "172.16.16.16"
  # config.vm.provision :shell, :path => "bootstrap.sh"
end
