#!/usr/bin/env bash

set -e
set -o pipefail

echo "Downloading dependencies..."
swift build --fetch
echo "Fixing SPM bug..."
rm -rf Packages/*/Tests
echo "Building..."
swift build --configuration release
