<!DOCTYPE html>
<html>
  <head><title>Fortunes</title></head>
  <body>
    <table>
        <tr>
            <th>id</th>
            <th>message</th>
        </tr>
        <?php foreach($data['fortunes'] as $fortune){ ?>
            <tr>
                <td><?php echo $fortune['id']; ?></td>
                <td><?php echo filter_var($fortune['message'], FILTER_SANITIZE_SPECIAL_CHARS); ?></td>
            </tr>
        <?php } ?>
    </table>
  </body>
</html>
