[framework]
name = "gnosis-uring"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database_os = "Linux"
database = "None"
os = "Linux"
orm = "Raw"
platform = "gnosis-uring"
webserver = "gnosis-uring"
versus = "may-minihttp"
