# frozen_string_literal: true

source "https://rubygems.org"

gem "hanami", "~> 2.3"
gem "hanami-router", "~> 2.3"
gem "hanami-controller", "~> 2.3"
gem "hanami-db", "~> 2.3"
gem "hanami-validations", "~> 2.3"
gem "hanami-view", "~> 2.3"

gem "dry-types", "~> 1.0", ">= 1.6.1"
gem "puma"
gem "rake"

gem "rom", "~> 5.3"
gem "rom-sql", "~> 3.6"
gem "pg"
