source 'https://rubygems.org'

gem 'rake'
gem 'hanami',       '~> 1.0'
gem 'hanami-model', '~> 1.0'

gem 'mysql2'

gem 'rom-sql'

group :production do
  gem 'puma', "~> 3.9.1"
  gem 'unicorn'
  gem 'thin'
end
