source 'https://rubygems.org'

gem 'rails', '~> 8.0.0'
gem 'redis', '~> 5.0'
gem 'tzinfo-data'

group :mysql do
  gem 'trilogy', '~> 2.8.1'
end

group :postgresql do
  gem 'pg', '~> 1.5'
end

group :falcon do
  gem 'falcon', '~> 0.47', require: false
end

group :puma do
  gem 'puma', '~> 6.4', require: false
end

group :agoo do
  gem 'agoo', require: false
  gem 'rackup'
end
