source 'https://rubygems.org' do
  gem 'listen', '~> 3.3', group: :development
  gem 'mysql2', '0.5.3', group: :mysql
  gem 'oj', '3.11.2'
  gem 'pg', '1.2.3', group: :postgresql
  gem 'puma', '5.2.1'
  gem 'rails', '6.1.3'
  gem 'tzinfo-data', '1.2021.1'
end