source 'http://rubygems.org'

platforms :jruby do
  gem 'activerecord-jdbc-adapter', '~> 1.3.7'
  gem 'jdbc-mysql', '5.1.38'
  gem 'torqbox', '0.1.7'
end

platforms :ruby do
  gem 'mysql2', '0.3.16'
  gem 'passenger', '4.0.44'
  gem 'unicorn', '4.8.3'
end

gem 'rails', '3.2.18'
