source 'http://rubygems.org'

platforms :jruby do
  gem "activerecord-jdbcmysql-adapter", "~> 1.3.5", :require => false
  gem 'torqbox', '0.1.7'
  gem "trinidad", "1.4.6"
end

platforms :ruby do
  gem 'mysql2', '0.3.11'
  gem "unicorn", "4.6.2"
  gem "thin", "~> 1.6.1"
end

gem 'activerecord', '4.0.2', :require => 'active_record'
gem "activerecord-import", "~> 0.4.1"
gem "grape", "0.6.1"
gem 'rack', '1.5.1'
gem 'json', '1.7.6'
gem "puma", "~> 2.7.1"


