source 'https://rubygems.org'

gem 'activerecord', '~> 8.1.0', :require => 'active_record'
gem 'grape', '~> 3.0'
gem 'pg'
gem 'json'

group :iodine, optional: true do
  gem "iodine", "~> 0.7", require: false
end

group :puma, optional: true do
  gem "puma", "~> 7.1", require: false
end
