# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative '../vagrant-common/checks'
require_relative '../vagrant-common/core'

provider = get_provider
check_provider_needs(provider)

Vagrant.configure("2") do |config|

  config.vm.provision :file do |file|
      file.source = "../vagrant-common/custom_motd.sh"
      file.destination = "~/.custom_motd.sh"
  end
  
  provision_bootstrap(config, 'all')

  provider_virtualbox(config, 'all')

  provider_aws(config, 'integrated')
  
end
