# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'core'

Vagrant.configure("2") do |config|

  config.vm.provision :file do |file|
      file.source = "custom_motd.sh"
      file.destination = "~/.custom_motd.sh"
  end

  config.vm.network "private_network", ip: "172.16.0.16"
  config.vm.network :forwarded_port, guest: 8080, host: 28080

  provision_bootstrap(config)
  provider_virtualbox(config)
  provider_libvirt(config)

end
