[framework]
name = "x-gnosis"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database_os = "Linux"
database = "None"
os = "Linux"
orm = "Raw"
platform = "Node.js"
webserver = "x-gnosis"
versus = "nodejs"

[postgresql]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
urls.cached_query = "/cached-queries?count="
approach = "Realistic"
classification = "Platform"
database_os = "Linux"
database = "Postgres"
os = "Linux"
orm = "Raw"
platform = "Node.js"
webserver = "x-gnosis"
versus = "nodejs"
