source 'https://rubygems.org'

gem 'oj'
gem 'passenger', '~> 6.0', :platforms=>[:ruby, :mswin], :require=>false
gem 'puma', '~> 6.4', :require=>false
gem 'sequel', '~> 5.0'
gem 'sinatra', '~> 3.0', :require=>'sinatra/base'
gem 'unicorn', '~> 6.1', :platforms=>[:ruby, :mswin], :require=>false

group :mysql do
  gem 'mysql2', '~> 0.5', :platforms=>[:ruby, :mswin]
end

group :postgresql do
  gem 'pg', '~> 1.5', :platforms=>[:ruby, :mswin]
  gem 'sequel_pg', '~> 1.6', :platforms=>:ruby, :require=>false
end
