source 'https://rubygems.org'

gem 'jdbc-mysql', '~> 5.1.38', :platform => 'jruby', :require => 'jdbc/mysql'
gem 'json', '~> 1.8.3', :require => 'json/ext'
gem 'mysql2', '~> 0.4.0', :platform => 'ruby'
gem 'puma', '~> 2.15.3'
gem 'sequel', '~> 4.28'
gem 'sinatra', '~> 1.4.6', :require => 'sinatra/base'
gem 'slim', '~> 3.0.6'
