requires 'Feersum', '== 1.503';
requires 'JSON::XS', '== 4.03';
requires 'DBD::MariaDB', '== 1.23';
requires 'DBD::Pg', '== 3.18.0';
requires 'AnyEvent', '== 7.17';
requires 'Async::Interrupt', '== 1.26';
requires 'Text::Xslate', '== v3.5.9';
requires 'LMDB_File', '== 0.13';
