source 'https://rubygems.org'

gem 'json', '~> 2.8'
gem 'sequel', '~> 5.0'
gem 'rack', '~> 3.1'

group :mysql, optional: true do
  gem 'trilogy', '~> 2.9', platforms: [:ruby, :windows]
end

group :postgresql, optional: true do
  gem 'pg', '~> 1.5', platforms: [:ruby, :windows]
  gem 'sequel_pg', '~> 1.6', platforms: :ruby, require: false
end

group :puma, optional: true do
  gem 'puma', '~> 6.5', require: false
end
