source 'https://rubygems.org'

gem 'json', '~> 2.0'
gem 'passenger', '~> 5.1', :platforms=>[:ruby, :mswin], :require=>false
gem 'puma', '~> 6.4', :require=>false
gem 'sequel', '~> 5.0'
gem 'rack', '2.0.8'
gem 'unicorn', '~> 5.2', :platforms=>[:ruby, :mswin], :require=>false

group :mysql do
  gem 'jdbc-mysql', '~> 5.1', :platforms=>:jruby, :require=>'jdbc/mysql'
  gem 'mysql2', '~> 0.4', :platforms=>[:ruby, :mswin]
end

group :postgresql do
  gem 'jdbc-postgres', '~> 9.4', :platforms=>:jruby, :require=>'jdbc/postgres'
  gem 'pg', '~> 0.19', :platforms=>[:ruby, :mswin]
  gem 'sequel_pg', '~> 1.6', :platforms=>:ruby, :require=>false
end
